export type Point = { x: number; y: number };
export type Corners = [Point, Point, Point, Point];
export type Filter = 'readable' | 'gray' | 'color' | 'binary';
export type Recipe = { points: Corners; rotation: 0 | 90 | 180 | 270; filter: Filter; brightness: number; contrast: number };
export type Day = { id: string; documentDate: string; zoneId: string; createdAt: string; updatedAt: string };
export type Asset = { id: string; kind: 'original' | 'rendered' | 'pdf'; blob: Blob; mime: string; byteCount: number; sha256: string; width?: number; height?: number; createdAt: string };
export type Page = { id: string; dayId: string; orderIndex: number; capturedAt: string; title: string; originalAssetId: string; activeRevisionId?: string; state: 'DRAFT' | 'READY' | 'DRAFT_UNSUPPORTED'; deletedAt?: string };
export type Revision = { id: string; pageId: string; originalHash: string; recipe: Recipe; filterVersion: 1; renderedAssetId: string; createdAt: string };
export type PdfExport = { id: string; dayId: string; displayName: string; orderedRevisionIds: string[]; orderedPageIds?: string[]; fingerprint: string; assetId: string; status: 'READY'; createdAt: string };
export type Job = { id: string; kind: 'pdf'; state: 'RUNNING' | 'VERIFYING' | 'READY' | 'INTERRUPTED' | 'FAILED' | 'CANCELED'; inputSnapshot: string[]; fencingToken: number; progress: number; createdAt: string; errorCode?: string };
export type IngestIntent = { id: string; dayId: string; startedAt: string; status: 'WAITING' | 'RECEIVED' | 'CANCELED' };
export type ShareEvent = { id: string; exportId: string; action: 'share' | 'download'; result: 'requested' | 'handed-off' | 'canceled' | 'failed'; requestedAt: string };
export type BackupEvent = { id: string; dayId: string; packageId: string; result: 'requested' | 'verified-import'; createdAt: string };
export type AppMeta = { key: 'app'; dataFormatVersion: number; minReaderVersion: number; generation: number; lease?: { owner: string; token: number; expires: number }; lastBuild?: string };
export const FORMAT_VERSION = 1;
export const MAX_PDF_PAGES = 10;
export const MAX_INPUT_BYTES = 50 * 1024 * 1024;
export const MAX_INPUT_PIXELS = 24_000_000;
export const now = () => new Date().toISOString();
export const id = () => crypto.randomUUID();
export const fullCorners = (): Corners => [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 0, y: 1 }];
export const defaultRecipe = (): Recipe => ({ points: fullCorners(), rotation: 0, filter: 'readable', brightness: 0, contrast: 1 });
